[build]
builder = "nixpacks"
buildCommand = "pnpm build"
watchPatterns = ["src/**", "libs/**"]

[deploy]
startCommand = "pnpm start:dev"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
