name: Test

on: push

jobs:
  test:
    environment: env
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install modules
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Testing
        run: pnpm test
